export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";

export const GET_CURRENT_EVENT = "GET_CURRENT_EVENT";
